### ISSUE TITLE
[Feature] docker compose tun2socks+wireguard

### ISSUE THREAD

**Issue by mifrith** [xjasonlyu/tun2socks#402]
### Description

```
services:
  tun2socks:
    image: ghcr.io/xjasonlyu/tun2socks:latest
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
        - '/dev/net/tun:/dev/net/tun'
    environment:
      - LOGLEVEL=info             
      - TUN=tun0                  
      - ADDR=198.18.0.1/15        
      - MTU=9000                 
      - PROXY=***
    ports:
      - 13235:51820/udp
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    container_name: tun2socks
    dns:
      - 8.8.8.8
      - 4.4.4.4
  
  proxy-wg:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: proxy-wg
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - SERVERPORT=51820
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.15.1.0
      - ALLOWEDIPS=10.15.1.0/24
      - PERSISTENTKEEPALIVE_PEERS=all
      - PEERS=gateway
      - LOG_CONFS=true
    volumes:
      - /docker/tun2socks/wg/config:/config
      - /docker/tun2socks/wg/modules:/lib/modules
    restart: unless-stopped
    network_mode: service:tun2socks
```
Greetings!
I'm trying to combine tun2socks and WG in docker. When wg tries to connect, the internal address is routed to the proxy. Please tell me how to exclude it from routing?

`tun2socks  | time="2024-09-04T10:02:12+03:00" level=info msg="[UDP] 198.18.0.1:51820 <-> 10.0.100.1:51820"`
